INSERT INTO `areas` VALUES (1, 1, 'Base de Datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (2, 2, 'Comercio Electrónico', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (3, 3, 'Computación Gráfica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (4, 4, 'Evaluación y Auditoria de Sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (5, 5, 'Ingeniería de Producción', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (6, 6, 'Ingeniería de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (7, 7, 'Inteligencia Artificial', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (8, 8, 'Interacción Humano Computador', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (9, 9, 'Investigación Operativa', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (10, 10, 'Matemática Computacional', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (11, 11, 'Programación en Internet', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (12, 12, 'Redes y Sistemas Distribuidos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (13, 13, 'Simulación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (14, 14, 'Sistemas de Información', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (15, 15, 'Tecnologías de Control', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (16, 16, 'Teoría de la Computación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (17, 17, 'Bases de Datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (18, 18, 'Bases de Datos Orientados a Objetos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (19, 22, 'Sistemas Multimedios e Hipermedios', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (20, 23, 'Sintesis de Imagenes', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (21, 24, 'Animación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (22, 25, 'Procesamiento de Imagenes', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (23, 26, 'Modelamiento Geometrico', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (24, 27, 'Sistemas CAD', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (25, 28, 'Dise&ntilde,o de Interfaces', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (26, 29, 'Realidad Virtual', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (27, 30, 'Antropometría', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (28, 31, 'Ergonomía', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (29, 32, 'Fisiología', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (30, 33, 'Interfaces Cooperativas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (31, 34, 'Interfaces de Usuario', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (32, 35, 'Psicología Cognitiva', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (33, 36, 'Arquitectura de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (34, 37, 'Desarrollo de Sistemas Orientados a Objetos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (35, 38, 'Especificación y Dise&ntilde,o de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (36, 39, 'Gerencia del Proceso de Desenvolvimiento y Mantenimiento de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (37, 40, 'Metodologías de Programación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (38, 41, 'Objetos Distribuidos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (39, 42, 'Reingeniería', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (40, 44, 'Sistemas de Información Geográfica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (41, 46, 'Algoritmos Genéticos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (42, 47, 'Autómatas Celulares', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (43, 48, 'Lógica Matemática', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (44, 49, 'Lógicas no Clásicas y Probadores de Teoremas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (45, 51, 'Procesamiento de Lenguaje Natural', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (46, 52, 'Redes Neuronales', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (47, 53, 'Robótica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (48, 54, 'Sistemas Bayesianos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (49, 55, 'Sistemas de Programación de Producción', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (50, 57, 'Logística', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (51, 58, 'Planeamiento y Control de Producción', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (52, 59, 'Sistemas de Gestión de Cálidad y Producción', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (53, 60, 'Contabilidad', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (54, 61, 'Estadística', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (55, 62, 'Métodos Númericos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (56, 63, 'Proyectos y Análisis de Algoritmos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (57, 64, 'Comunicación de Datos: Protocolos y Sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (58, 65, 'Procesamiento Paralelo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (59, 66, 'Programación Concurrente', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (60, 70, 'Control y Automatización Industrial', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (61, 71, 'Microcontroladores', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (62, 72, 'Sistemas de Tiempo Real', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (63, 73, 'Algoritmos Geométricos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (64, 74, 'Animación de Algoritmos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (65, 75, 'Compiladores', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (66, 76, 'Construcción de Compiladores Orientados a Objeto', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (67, 77, 'Especificación Formal de Lenguajes de Programación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (68, 78, 'Lenguaje Natural', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (69, 79, 'Métodos Formales de la Ingeniería de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (70, 80, 'Modelamiento del Proceso de Desenvolvimiento de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (71, 83, 'Portales Web', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (72, 84, 'Paradigma Orientado a Objetos', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (73, 85, 'Bioinformatica', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (74, 86, 'Interfaces Cooperativas', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (75, 87, 'Telecomunicaciones ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (76, 91, 'Generacion de Codigo Interfaz ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (77, 92, 'Vida Artificial  ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (78, 93, 'Ingenieria de Requerimientos ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (79, 94, 'Ambientes automatizados  ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (80, 95, 'Sistemas Evolutivos', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (81, 96, 'Base deDatos Temporales', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (82, 97, 'Base de Datos Distribuidos', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (83, 98, 'Matematica computacional', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (84, 99, 'Base de Datos Multidimensional', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (85, 100, 'Programación Funcional ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (86, 102, 'Sistemas Operativos ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (87, 103, 'Sistemas Operativos de PC ', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (88, 104, 'Sistemas académicos', 'El proposito de estos sistemas es la capacitacion de los estudiantes en el uso manejo, construción, modificación y diseño de sistemas operativos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (89, 105, 'Sistemas transaccionales', 'Estos sistemas basan su funcionamiento en el tipo de transacciones que realizan', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (90, 106, 'Recuperación de la información', 'Sistemas cuya problematica central en la manera en que recuperan la información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (91, 108, 'Programación para Internet', 'Todo lo referente a la programación en Internet', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (92, 109, 'Simulación de Sistemas', 'El uso de modelos matemáticos para la simulación de sistemas ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (93, 110, 'Automatización de procesos', 'En esta área se tratan los temas de automatización de procesos en todos los campos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (94, 111, 'Bases de Datos Dinámica', 'Bases de Datos Dinámica', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (95, 112, 'Sistema de Gestión empresarial', 'D', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (96, 113, 'Base de Datos Relacionales', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (97, 114, 'Sistemas Administrativos', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (98, 115, 'Métodos numéricos algebraicos', 'Sin informacion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (99, 116, 'Ingeniería de Sistemas', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (100, 117, 'Ingenieria de la usabilidad', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (101, 118, 'Usabilidad', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (102, 119, 'Trabajos Colaborativos', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (103, 120, 'Arquitectura de Computadoras', 'Sin informacion.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (104, 123, 'Evaluación y Auditoria de Sistemas', ' ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (105, 124, 'Sistema educativo', 'Sin Informacion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (106, 125, 'Servidores de Audio', 'Sin Información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (107, 126, 'Sistemas Inteligentes', 'Sin Información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (108, 127, 'Interfaz de Usuario', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (109, 128, 'Accesibilidad', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (110, 129, 'Seguridad en Redes', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (111, 130, 'Trabajo Colaborativo', 'Sin información', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (112, 131, 'Desarrollo e Investigación', 'Sin descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (113, 133, 'Redes de Optimización', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (114, 134, 'Sistemas Multiagente', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (115, 135, 'Comunidades Virtuales', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (116, 136, 'Tecnología de Información y Comunicación(TIC)', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (117, 137, 'Diseño de Sistemas', 'Sin descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (118, 138, 'Entornos virtuales', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (119, 139, 'Análisis de Patrones', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (120, 140, 'Educación Superior en Inf.', 'Sin descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (121, 141, 'Epistemología', 'Sin descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (122, 142, 'Meto. de diseño curricular', 'Sin descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (123, 143, 'Tecnologías de Desarrollo', 'Sin descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (124, 144, 'Procesos de Desarrollo', 'Procesos de desarrollo de software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (125, 145, 'Metodología de desarrollo', 'Metodologías de desarrollo de software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (126, 146, 'Frameworks', 'Uso de frameworks para el desarrollo de aplicaciones', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (127, 148, 'Computación Gráfica', '-', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (128, 149, 'Seguridad Informática', 'Seguridad Informática en Sistemas Computacionales', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (129, 150, 'Criptografía Aplicada', '-', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (130, 151, 'Gestión de Sistemas', 'La información que se maneja en una base de datos de una entidad financiera es de vital importancia, para ello se lleva un proceso el cual se desarrollará para verificar como se encuentran los datos, como actuarán ellos tras algún percance que pueda ocurrir y sobre todo la continuidad que puede tener la entidad con estos problemas y como se resolverán para que no ocurran en un futuro y mantenerlos controlados.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (131, 152, 'Accesibilidad Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (132, 153, 'Motores de Búsqueda', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (133, 154, 'Ingeniería de Software Educativo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (134, 155, 'Servicios Web', 'SW es un conjunto de protocolos y estandares que sirven para intercambiar datos entre aplicaciones.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (135, 156, 'Sistemas de Telecomunicaion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (136, 157, 'Sistemas de Telecomunicacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (137, 158, 'Migracion de contenidos de CMS', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (138, 159, 'Sistemas de Informacion Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (139, 160, 'Planificacion, Control y Gestion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (140, 161, 'Música Artificial', 'Creacion de musica a travez de algoritmos que proveen mecanismos de composición', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (141, 162, 'Gestión de Transacciones', 'Se trata el problema de asegurar la bd en un estado consistente aún en casos de acceso concurrente', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (142, 163, 'Simulación de Redes', 'Sin descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (143, 164, 'Visión por Computador', 'Descripción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (144, 165, 'Ingenieria de tecnologia e informacion(IT)', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (145, 166, 'Modelación y simulación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (146, 167, 'Dinámica de sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (147, 168, 'Contend Management Systems(CMS)', 'Sistemas de administración de contenido, archivos, páginas web, blogs,entre otros', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (148, 169, 'Sistemas de Telecomunicaciones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (149, 170, 'Sistemas de Información Geográfico', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (150, 171, 'Ciencias Juridicas', 'Ciencias Juridicas', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (151, 172, 'Programación y Aplicaciones Web', 'El estudio y programacion de aplicaciones web', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (152, 173, 'Estandares Web', 'Especifica los estandares formales y otras especificaciones que definen  aspectos de la worl wide we', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (153, 174, 'Tecnologia Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (154, 175, 'PLANEACIÓN Y CONTROL DE PRODUCCIÓN DE LA MANO DE OBRA DIRECTA.', 'Controlar la parte productiva del personal de planta', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (155, 176, 'Redes Multimedia', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (156, 177, 'E-learning', 'aprendizaje por internet', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (157, 178, 'Didáctica y Multimedia Interactiva', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (158, 179, 'business intelligence', 'Se denomina inteligencia empresarial o inteligencia de negocios o BI', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (159, 180, 'Dinamica de sistemas', 'es una metodología para la construcción de modelos de simulación para sistemas complejos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (160, 181, 'Ingenieria de Calidad', 'Referido a control de calidad en productos de software.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (161, 182, 'Ingeniería de Calidad', 'Referido a control de calidad de productos de software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (162, 183, 'Business Intelligence', 'Se denomina inteligencia empresarial o inteligencia de negocios o BI', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (163, 184, 'Domótica', 'Se entiende por domótica al conjunto de sistemas capaces de automatizar una vivienda, aportando servicios de gestión energética, seguridad, bienestar y comunicación', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (164, 185, 'Telemetría', 'La telemetría es una tecnología que permite la medición remota de magnitudes físicas y el posterior envío de la información hacia el operador', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (165, 186, 'Base de Datos Relacionales Difusas', 'La Base de Datos Relacionales Difusas, nos ayuda a poder realizar consultas con tipos de datos imprecisa.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (166, 187, 'Seguridad en base de datos', 'Seguridad en base de datos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (167, 188, 'Electronica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (168, 189, 'Multimedia Interactivo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (169, 190, 'Seguridad en Aplicaciones Web', 'Seguridad en Aplicaciones Web', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (170, 191, 'Administracion de Servidores', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (171, 192, 'Diseño Avanzado de Software', 'Diseño Avanzado de Software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (172, 193, 'Interaccion Humano-Computadora', 'Interaccion Humano-Computadora', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (173, 194, 'Linguistica Computacional', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (174, 195, 'sistemas orientados a objetos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (175, 196, 'Interfaces Gráficas de Usuario WEB', 'Interfaces Gráficas de Usuario WEB', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (176, 197, 'Gestión y Administración de Información', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (177, 198, 'Contabilidad de Costos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (178, 199, 'Estados Financieros', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (179, 200, 'Sistemas de informacion Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (180, 201, 'Arquitectura de la Informacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (181, 202, 'Seguridad con sistemas informaticos', 'Seguridad domiciliaria y empresarial con sistemas informaticos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (182, 203, 'Programacion Funcional Aplicada', 'Desarrollo de aplicaciones utilizando lenguajes funcioanles.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (183, 204, 'simulacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (184, 205, 'Aeronáutica', 'La aeronáutica es la ciencia relacionada con el estudio, diseño, manufactura y técnicas de control de aeronaves.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (185, 206, 'Infografía', 'Imágenes generadas por ordenador', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (186, 207, 'Redes de Computadoras', 'Estudio de los niveles del modelo tpc/ip', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (187, 208, 'bd new', 'asd asd', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (188, 209, 'Programacion y Aplicaciones Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (189, 210, 'Contenedor CMS', 'Un sistema de gestión de contenidos(content management system, abreviado CMS) es un programa que permite crear una estructura de soporte(framework) para la creación y administración de contenidos, principalmente en páginas web, por parte de los participantes.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (190, 211, 'Redes Inalambricas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (191, 212, 'Toma de Desiciones Administrativas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (192, 213, 'Reconocimiento de voz', 'Reconocimiento de voz', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (193, 214, 'Reconocimiento de la voz', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (194, 215, 'Desarrollo de Software Inteligente ', 'Aplicación de la Inteligencia Artificial al desarrollo de software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (195, 216, 'Ambientes automatizados de apoyo para productos de construcción de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (196, 217, 'Programacion Movil', 'Desarrollo de aplicaciones para los dispocitivos moviles(Celulares)', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (197, 218, 'Seguridad biometrica', 'Desarrollo de aplicaciones de seguridad utilizando biometria de tecleo', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (198, 219, 'Software Educativo', 'En esta área se engloban todo software orientados a la educación en sus diferentes grados.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (199, 220, 'Seguridad  y Gestion de Redes', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (200, 221, 'Programación abajo Nivel', 'Uso del lenguaje de segunda generación assembler ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (201, 222, 'taller de programación  a bajo nivel', 'Se trata de aplicar los conocimientos adquiridos en la programación con assembler, aprovechando al maximo la arquitectura de un computador y el sistema operativo.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (202, 223, 'Aplicaciones WEB', 'Aplicaciones creadas para el servicio web, orientadas a proveer un servicio a los usuarios.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (203, 224, 'Servicio WEB', 'Servicios orientados a los usuarios, con fines educativos, informativos, etc.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (204, 225, 'Sistema de procesamiento de transacciones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (205, 226, 'Educación Superior en Ingeniería de Sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (206, 227, 'patrones de diseño', 'El Patrón de Diseño DAO busca el acoplamiento con el patrón Modelo Vista Controlador(MVC). Creando las clases necesarias para el Modelo(CRUD), Controlador(Action), Vista, JSP.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (207, 228, 'Informatica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (208, 229, 'Sistema  de Apoyo a la Toma de decisiones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (209, 230, 'Redes de computadoras intranet', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (210, 231, 'Aplicacion Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (211, 232, 'ingenieria de software', 'descripcion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (212, 233, 'sistema web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (213, 234, 'M-Commerce, M-Payment', 'Areas en las que se realizan distintas transacciones concretamente de pago y compra de bienes o servicios utilizando como herramineta un dispositivo movil. ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (214, 235, 'Sistema de Informacion Administrativo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (215, 236, 'Android', 'Android es un sistema operativo orientado a dispositivos móviles basado en una versión modificada del núcleo Linux.Inicialmente fue desarrollado por Android Inc., compañía que fue comprada después por Google, y en la actualidad lo desarrollan los miembros de la Open Handset Alliance(liderada por Google).\r\nLa presentación de la plataforma Android se realizó el 5 de noviembre de 2007 junto con la fundación Open Handset Alliance, un consorcio de 48 compañías de hardware, software y telecomunicaciones comprometidas con la promoción de estándares abiertos para dispositivos móviles.Esta plataforma permite el desarrollo de aplicaciones por terceros a través del SDK, proporcionada por el mismo Google, y mediante el lenguaje de programación Java.Una alternativa es el uso del NDK(Native Development Kit) de Google para emplear el lenguaje de programación C.\r\n\r\nEl código fuente de Android está disponible bajo diversas licencias de software libre y código abierto destacando la versión 2 de la licencia Apache.\r\nCaracteristicas:\r\n    * Framework  de aplicaciones: permite reutilización y reemplazo de componentes.\r\n    * Máquina virtual Dalvik: optimizada para dispositivos móviles.\r\n    * Navegador integrado: basado en el motor de código abierto WebKit.\r\n    * Gráficos optimizados, con una biblioteca de gráficos 2D, gráficos 3D basado en la especificación OpenGL ES 1.0(aceleración por hardware opcional).\r\n    * SQLite para almacenamiento de datos estructurados.\r\n    * Soporte para medios con formatos comunes de audio, vídeo e imágenes planas(MPEG4, H.264, MP3, OGG, AAC, AMR, JPG, PNG, GIF)\r\n    * Telefonía GSM(dependiente del hardware)\r\n    * Bluetooth, EDGE, 3G, y WiFi(dependiente del hardware)\r\n    * Cámara, GPS, brújula, y acelerómetro(dependiente del hardware)\r\n    * Ambiente rico de desarrollo incluyendo un emulador de dispositivo, herramientas para depurar, perfiles de memoria y rendimiento, y un complemento para el IDE Eclipse.\r\n    * Pantalla táctil\r\n    * Android Market permite que los desarrolladores pongan sus aplicaciones, gratuitas o de pago, en el mercado a través de esta aplicación accesible desde la mayoría de los teléfonos con Android.\r\n', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (216, 237, 'Telecomunicaciones', 'Se refiere a todo procedimiento que permite a un usuario hacer llegar a uno o varios usuarios determinados(ej. telefonía) o eventuales(ej. radio, televisión), información de cualquier naturaleza(documento escrito, impreso, imagen fija o en movimiento, videos, voz, música, señales visibles, señales audibles, señales de mandos mecánicos, etc.), empleando para dicho procedimiento, cualquier sistema electromagnético para su transmisión y/o recepción(transmisión eléctrica por hilos, radioeléctrica, óptica, o una combinación de estos diversos sistemas)', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (217, 238, 'Sistemas de Gestion Web', 'Toda informacion sera manejada mediante el internet en linea con el apoyo de la herramienta Zend para Php', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (218, 239, 'Programación Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (219, 240, 'Reconocimiento de Voz', 'ninguna', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (220, 241, 'Redes de computadoras e internet', 'Redes de computadoras que se relacionan con internet', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (221, 242, 'Tecnologia Informatica en Educacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (222, 243, 'Sistema de Produccion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (223, 244, 'Entornos Virtuales de Aprendizaje', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (224, 245, 'Workflow', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (225, 246, 'Redes de Comunicacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (226, 247, 'Desarrollo Web', 'Desarrollo Web', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (227, 248, 'VOZ IP', 'En esta area esta relacionanda con las telecomunicaciones el cual utiliza la transmicion de voz sobre ips como tambien tipos de compresion para la voz el cual seran transmitidos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (228, 249, 'Telefonia IP', 'La telefonía IP reúne la transmisión de voz y de datos, lo que posibilita la utilización de las redes informáticas para efectuar llamadas telefónicas. Además, ésta tecnología al desarrollar una única red encargada de cursar todo tipo de comunicación, ya sea de voz, datos o video, se denomina red convergente o red multiservicios.La telefonía IP surge como una alternativa a la telefonía tradicional, brindando nuevos servicios al cliente y una serie de beneficios económicos y tecnológicos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (229, 250, 'Centrales Telefonicas IP', 'En la nueva era de las comunicaciones digitales, las centrales de telefonía han evolucionado, hasta convertirse en potentes maquinas de enrutamiento y gestión de llamadas, capaces de usar telefonía IP', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (230, 251, 'Aseguramiento de la calidad del software', 'Area encargada de validar , verificar y controlar la calidad del producto de software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (231, 252, 'Centrales Telefónicas IP', 'En la nueva era de las comunicaciones digitales, las centrales de telefonía han evolucionado, hasta convertirse en potentes maquinas de enrutamiento y gestión de llamadas, capaces de usar telefonía IP.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (232, 253, 'programacion web', 'permite realizar la comunicacion via paginas web mediante internet', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (233, 254, 'Aseguramiento de Calidad de Software.', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (234, 255, 'Aseguramiento de Calidad de Software', 'Control de Calidad', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (235, 256, 'Tecnología de Información y Comunicación(TIC) en la educación', 'Tecnologias de Informacion y Comunicacion(TIC) aplicadas a la educacion.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (236, 257, 'Diseño de interfaces', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (237, 258, 'Seguridad de la Informacion', 'Es el area que se encarga de buscar, formas de proteger la informacion de terceras personas, como con la criptografia, esteganografia, marcas de agua, etc.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (238, 259, 'Esteganografia', 'Esta tecnica es el arte y ciencia de enviar informacion secreta de tal forma que nadie fuera de quien lo envia y quien lo recibe sabe de su existencia, en contraste con la criptografia, en donde la existencia del mensaje es clara pero esta obscurecido. Por lo general la informacion  enviada de este tipo parece ser simplemente una imagen o foto. La esteganografia logra ocultar informacion en una imagen utilizando el bit menos significativo de cada color en los pixeles.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (239, 260, 'Aseguramiento de la Calidad del Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (240, 261, 'Computación Científica', 'Es el campo de estudio relacionado con la construcción de modelos matemáticos y técnicas numéricas para resolver problemas científicos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (241, 262, 'MODELO DIGITAL DEL TERRENO', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (242, 263, 'Programacion Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (243, 264, 'Programacion Web', 'programacion web', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (244, 265, 'Calidad de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (245, 266, 'Dinamica de Sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (246, 267, 'Sistemas Tutoriales', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (247, 268, 'Autoevaluación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (248, 269, 'Optimizacion Combinatoria', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (249, 270, 'Aseguramiento de la calidad de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (250, 271, 'Aplicaciones Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (251, 272, 'Desarrollo de Aplicaciones Web', 'Desarrollo de Aplicaciones Web', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (252, 273, 'Diseño de compiladores', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (253, 274, 'Sistemas Colaborativos', 'sistemas colaborativos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (254, 276, 'Estrategias Heurísticas para la toma de  decisiones ', 'Se comportan como recursos organizativos del proceso de resolución, que contribuyen especialmente a determinar la vía de solución del problema abordado', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (255, 277, 'Sistemas Expertos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (256, 278, 'Sistema Experto', 'sistema experto', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (257, 279, 'Diseño e Implementación de un Compilador', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (258, 280, 'Telefonía Ip', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (259, 281, 'telecomunicaciones', 'Servicios de telecomuniciones', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (260, 282, 'Control de calidad de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (261, 283, 'Material Educativo Computarizado(M.E.C.)', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (262, 284, 'Monitoreo de Servidores', 'Herramientas útiles para los administradores de servidores o personal de TI', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (263, 285, 'Ambientes automatizados de apoyo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (264, 286, 'Control de Calidad del Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (265, 287, 'Aseguramiento de la Calidad de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (266, 288, 'Sistemas de Aprendizaje', 'Sistemas de aprendizaje', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (267, 290, 'Inteligencia Artificial, Base de Datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (268, 291, 'Redes', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (269, 292, 'Redes de Telecomunicaciones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (270, 293, 'Sistemas Operativos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (271, 294, 'Transferencia de Datos Protocolo IP', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (272, 295, 'Sistema de Escaneado Optimo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (273, 296, 'Control de Calidad de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (274, 297, 'Servicio Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (275, 298, 'CMS', 'Content Management System', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (276, 299, 'Software educativo', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (277, 300, 'Procesamiento de datos Meteorológicos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (278, 301, 'Software de Gestión', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (279, 302, 'Diseño e implementacion de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (280, 303, 'Web semántica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (281, 304, 'Redes de Datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (282, 305, 'Tecnicas de Animacion 3D', 'se hace uso de las tecnicas de animacion 3D como ser Keyframe,procedural las cuales permiten generar una animacion en 3D haciendo uso de herramientas de diseño 3D,tambien se puede hacer uso de la tecnica de rotoscopia el cual captura informacion de movimiento mediante sensores de objetos reales pero este requiere de equipos especiales.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (283, 306, 'Calidad de software', 'evaluacion de material multimedia, para obtener la calidad de la aplicación.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (284, 307, 'Ambientes automatizados de apoyo para productos de construccion de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (285, 308, 'Base de Datos, Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (286, 309, 'Herramienta SIG', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (287, 310, 'Sistemas Integrados de Gestion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (288, 311, 'Sistemas web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (289, 312, 'Control de calidad de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (290, 313, 'Sistemas de Información geográfica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (291, 314, 'Sistemas de Gestión', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (292, 315, 'Sistemas Colaborativos en la Educación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (293, 316, 'Computación en la nube', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (294, 317, 'Telefonía y Comunicaciones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (295, 318, 'Sistema de Reportes', 'En la ingenieria de software se necesita gráficas para analizar el trabajo de cada desarrollador, que representados en reportes gráficos son mas entendibles para los administradores de equipos de desarrollo', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (296, 319, 'Redes Moviles', 'Esta subárea se refiere a la interconexion de celulares por medio wifi.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (297, 320, 'Realidad Aumentada', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (298, 321, 'Sistema Web', 'Un sistema web es el conjunto de tecnologias de la informacion y las comunicaciones que sirven de soporte a la utilizacion de Internet en el seno de la misma, tanto como herramienta para la obtencion y procesamiento de la informacion en la toma de decisiones como en la interrelacion de la empresa con su mercado y su entorno.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (299, 322, 'Redes de computadoras en internet', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (300, 323, 'Administración de servidores', 'Aplicaciones creadas sobre plataformas de dispositivos móviles para administrar servicios en servidores de producción', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (301, 324, 'programacion funcional', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (302, 325, 'Ingenieria de Produccion', 'Dentro del area de Sistemas de informacion se trabaja para dar soluciones al area de la ingenieria de produccion', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (303, 326, 'Sistemas Web', 'Similar a Desarrollo Web, con caracteristicas dinamicas y estaticas basados en la Web y gestion de Base de Datos.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (304, 327, 'Control de Calidad de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (305, 328, 'Sistemas de Soporte a la Administración', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (306, 329, 'Sistema de Archivos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (307, 330, 'Programación en la Nube', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (308, 331, 'Software para dispositivos móviles', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (309, 332, 'Desarrollo web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (310, 333, 'Mashups', 'En desarrollo web, un mashup es una página web o aplicación que usa y combina datos, presentaciones y funcionalidad procedentes de una o más fuentes para crear nuevos servicios. El término implica integración fácil y rápida, usando a menudo APIs abiertos y fuentes de datos para producir resultados enriquecidos que no fueron la razón original para la que fueron producidos los datos en crudo originales.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (311, 334, 'Web Scraping', 'Web Scraping es una técnica utilizada por softwares de computadora para extraer información de sitios webs', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (312, 335, 'Realidad aumentada', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (313, 336, 'Redes de distribucion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (314, 337, 'Aplicacion android', 'desarrollo de aplicaciones para Android', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (315, 338, 'Sistema CRM', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (316, 339, 'Metodos de Busqueda heuristica o solucion de problemas', 'En computación, dos objetivos fundamentales son encontrar algoritmos con buenos tiempos de ejecución y buenas soluciones, usualmente las óptimas. Una heurística es un algoritmo que abandona uno o ambos objetivos, por ejemplo, normalmente encuentran buenas soluciones, aunque no hay pruebas de que la solución no pueda ser arbitrariamente errónea en algunos casos, o se ejecuta razonablemente rápido, aunque no existe tampoco prueba de que siempre será así. Las heurísticas generalmente son usadas cuando no existe una solución óptima bajo las restricciones dadas(tiempo, espacio, etc.), o cuando no existe del todo.\r\nA menudo, pueden encontrarse instancias concretas del problema donde la heurística producirá resultados muy malos o se ejecutará muy lentamente. Aun así, estas instancias concretas pueden ser ignoradas porque no deberían ocurrir nunca en la práctica por ser de origen teórico. Por tanto, el uso de heurísticas es muy común en el mundo real.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (317, 340, 'Sistemas de apoyo a la docencia', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (318, 341, 'Accesibilidad audiovisual web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (319, 343, 'Compiladores e interpretadores', 'Sub area de compiladores e interpretadores\r\n\r\n', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (320, 344, 'Analisis y filtrado', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (321, 345, 'Interpretes y compiladores', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (322, 346, 'Ambientes automatizados de apoyo para construccion de productos de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (323, 347, 'Medios de Comunicacion Digitales', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (324, 348, 'Sistemas de gestión de calidad de producción.', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (325, 349, 'Investigación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (326, 350, 'Hidrología', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (327, 351, 'Recuperacion de la Informacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (328, 352, 'Automatización', 'Sistema tecnológico basado en la ingeniería y la informática, que proporciona una optimización de los procesos productivos mediante la regulación automática.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (329, 353, 'Redes de telecomunicaiones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (330, 354, 'Punto de Venta', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (331, 355, 'Simulacion de Sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (332, 356, 'Diseño de Aerogeneradores', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (333, 357, 'Ambientes automatizados de apoyo para productos de construcción de software ', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (334, 358, 'Ingeniería de yacimientos', 'La ingeniería de yacimientos es la parte fundamental de la ingeniería de petróleo, aplicando conocimientos científicos, permite  una explotación racional de las acumulaciones de hidrocarburos, para obtener su máxima recuperación al menor costo ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (335, 359, 'Data Science', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (336, 360, 'Procesamiento Informacion de Redes Sociales', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (337, 361, 'Sistema Multimedia', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (338, 362, 'Sistemas Virtuales', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (339, 363, 'Comunicacion de datos, Sistemas de tiempo real, Intranet/Internet', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (340, 364, 'E-Learning', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (341, 365, 'Modelo relacional de base de datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (342, 366, 'Aplicación Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (343, 367, 'Protocolos de acceso a directorio', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (344, 368, 'Sistema de Informacion Gerencial', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (345, 369, 'Automatizacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (346, 370, 'H.C.I', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (347, 371, 'Telefonia Movil, M-Payment, Modem Gateway', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (348, 372, 'Juegos Didacticos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (349, 373, 'Programacion y Aplicacion web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (350, 374, 'Computacion Paralela', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (351, 375, 'Semántica de datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (352, 376, 'Interacción persona-computador para educación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (353, 377, 'Composicion Algoritmica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (354, 378, 'Servidor OwnCloud', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (355, 379, 'Redes de telecomunicaciones', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (356, 380, 'Software para dispositivos Moviles', 'desarrollo de software para dispositivos moviles  usando metodos, tecnicas y teorias de ingeniera de software.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (357, 381, 'Administracion de inventarios', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (358, 382, 'Aplicacion movil', 'Aplicacion movil para el manejo de inventarios\r\n', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (359, 383, 'Tecnologías Web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (360, 384, 'Comunicación en Tiempo Real', 'Tecnologías web que permiten comunicación en tiempo real.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (361, 385, 'TICs en la educacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (362, 386, 'Computacion y Sociedad', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (363, 387, 'Ejercitación y Práctica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (364, 388, 'Planificación y Organización Empresarial', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (365, 389, 'Gestión Estratégica de Empresas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (366, 390, 'Técnologias de Información Educativa', 'Sistemas de información dedicada al estudio y apoyo a la educación mediante un sistema de información. ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (367, 391, 'Tecnologías de Información Educativa', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (368, 392, 'Taller de Programacion a Bajo Nivel', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (369, 393, 'Aplicacion de Sistemas Operativos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (370, 394, 'procesamiento de imagenes digitales', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (371, 395, 'Administrador de archivos', 'Sistema especializado en la administración de documentación, a partir de la cual se crea un repositorio, el que podrá ser accedido, compartido, eliminado según la necesidad o requerimientos del administrador o usuarios', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (372, 396, 'Sistemas basados en conocimiento', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (373, 397, 'Lingüística  Computacional', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (374, 398, 'Programación y Algoritmos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (375, 399, 'Sistemas de Telecomunicación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (376, 400, 'Minería de datos ', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (377, 401, 'Aplicacion Movil', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (378, 402, 'Informática de la salud', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (379, 403, 'TICs aplicadas a la Educación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (380, 404, 'Programacion Web reactiva', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (381, 405, 'Gestion y planificación de empresas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (382, 406, 'Television Digital', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (383, 407, 'Modelos de proceso', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (384, 408, 'Gestión de empresas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (385, 409, 'Internet', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (386, 410, 'Sistemas Distribuidos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (387, 411, 'Desarrollo de Software', 'Herramientas y recursos que son utilizados en el proceso de fabricación de software', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (388, 412, 'APIs para interfaz de usuario', 'Interfaz de usuario', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (389, 413, 'Tecnología de Información y Comunicación(TIC) de la educación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (390, 414, 'Sistemas de Información Web', 'Desarrollo de sistemas web', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (391, 415, 'TICs de la educación', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (392, 416, 'Tecnologia de Apoyo a Estadistica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (393, 417, 'Administración y gestión de proyectos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (394, 418, 'Aplicación Móvil', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (395, 419, 'modelacion de sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (396, 420, 'e-learning', 'El e-learning consiste en la educación y capacitación a través de Internet. Este tipo de enseñanza online permite la interacción del usuario con el material mediante la utilización de diversas herramientas informáticas.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (397, 421, 'Desarrollo de videojuegos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (398, 422, 'Enrutamiento', 'La función de enrutamiento es una función de la Capa 3 del modelo OSI. El enrutamiento es un esquema de organización jerárquico que permite que se agrupen direcciones individuales. Estas direcciones individuales son tratadas como unidades únicas hasta que se necesita la dirección destino para la entrega final de los datos. El enrutamiento es el proceso de hallar la ruta más eficiente desde un dispositivo a otro. El dispositivo primario que realiza el proceso de enrutamiento es el Router.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (399, 423, 'Lingüística Computacional  ', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (400, 424, 'Diseño', 'Patrones de diseño', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (401, 425, 'Sistemas Control de Procesos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (402, 426, 'Comercio electrónico', 'Comercio electrónico tambien conocido como e-commerce, conciste en la compra y venta de productos o servicios a traves de medios electrónicos tales como internet y otras redes informaticas', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (403, 427, 'Aplicacion de GPS', 'Aplicación de GPS(Sistema de posicionamiento global) en dispositivos móviles', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (404, 428, 'aprendizaje por computadora', 'el aprendizaje automático(Machine Learning) es una rama de la inteligencia artificial el cual busca desarrollar técnicas que permitan crear programas capaces de procesar y analizar grandes cantidades de datos para posteriormente agruparlas y consolidarlas en porciones pequeñas de información útil, que permita reconocer y decodificar patrones complejos y predecir tendencias o comportamientos futuros, estos programas deben aprender y mejorar con la experiencia a través el tiempo, refinando sus modelos que son usados para predecir los posibles resultados con el fin de facilitar la toma de decisiones inteligentes basadas en esa información.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (405, 429, 'Visión Artificial', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (406, 430, 'Aprendizaje automático', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (407, 431, 'Laboratorios virtuales basados en WWW.', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (408, 432, 'Base de Datos - Ingenieria de Software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (409, 433, 'Automatizacion de Procesos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (410, 434, 'control de procesos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (411, 435, 'Domotica', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (412, 436, 'Sistema en tiempo real y control de procesos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (413, 437, 'Ingenieria de control', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (414, 438, 'Programación en Ginga-NCL', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (415, 439, 'Computación Educativa', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (416, 440, 'Telefonía IP', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (417, 441, 'sistema de informacion administrativa web', 'es un conjunto de elementos orientados al tratamiento y administracion de datos e informacion ,organizados y listos para su uso posterior o un objetivo.\r\nQue formarian parte de algunas de las siguientes partes(personas , actividades, datos. etc), para obtener informacion mas exacta y mas clara al momento de utilizar dicha informacion.\r\nla parte de administrar esta informacion en el area web es que ayude y evite pasos extras al momento de manejo de informacion hace que sea dinamico las busqueadas y otros procedimientos de la misma aplicacion web.\r\n', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (418, 442, 'Aplicación Intranet ', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (419, 443, 'Prueba de intrusión', 'Es una práctica para poner a prueba un sistema informático, red o aplicación web para encontrar vulnerabilidades que un atacante podría explotar.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (420, 444, 'Encriptacion de datos', 'Es el proceso mediante el cual cierta informacion o texto sin formato es cifrado de forma que el resultado sea ilegible a menos que se conozca los datos necesarios para su interpretacion.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (421, 445, 'Programacion Ginga NCL/Lua', 'Ginga NCL/Lua herramienta desarrollada por la puc de Rio para el desarrollo de aplicaciones interactivas para Television Digital', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (422, 446, 'CSCW', 'Computer Supported Coopertive Work CSCW, Trabajo cooperativo asistido por computadora.\r\nCSCW es un Término utilizado para describir cualquier tecnología que combina recursos de hardware y software para permitir a grupos de personas colaborar y compartir tecnología.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (423, 447, 'Visualizacion de datos', 'La visualizacio&#769,n de datos trata de la creacio&#769,n de meta&#769,foras visuales y el estudio de comunicar la informacio&#769,n de manera ma&#769,s clara y efectiva a trave&#769,s de estas.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (424, 448, 'Herramienta y métodos de ingeniería de software', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (425, 449, 'Integracion de tecnologias moviles', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (426, 450, 'Entornos Virtuales de Aprendizaje ', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (427, 451, 'Planificación Automática', 'La planificación automática es una disciplina de la inteligencia artificial que tiene por objeto la producción de planes(es decir, una planificación), típicamente para la ejecución de un robot u otro agente.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (428, 452, 'Dinámica de Sistemas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (429, 453, 'Aplicaciones móviles', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (430, 454, 'aplicación móvil(app)', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (431, 455, 'Programación Móvil, GPS', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (432, 456, 'Television Digital Interactiva', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (433, 457, 'Procesamiento del lenguaje natural', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (434, 458, 'Aprendizaje de máquina', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (435, 459, 'Ingenieria Economica', 'Area de la matematica financiera muy usado en la toma de decisiones, el manejo de amortizaciones de deudas y manejo de las tasas de interes muy usado en la vida cotidiana. ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (436, 460, 'Aplicaciones Hibridas', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (437, 461, 'Teoría de Grafos', 'Teoría de Grafos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (438, 462, 'Redes aleatorias', 'Redes aleatorias', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (439, 463, 'Diseño de Interfaces - Desarrollo de Sistemas Orientados a Objetos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (440, 464, 'Gestion Administrativa', 'Gestion de los procesos administrativos', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (441, 465, 'Aplicación de Sistemas Operativos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (442, 466, 'Servicios Telematicos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (443, 467, 'Realidad Mixta', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (444, 468, 'Graficacion por Computadora', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (445, 469, 'Servicios Web REST', 'La Transferencia de Estado Representacional(REST - Representational State Transfer) fue ganando amplia adopción en toda la web como una alternativa más simple a SOAP y a los servicios web basados en el Lenguage de Descripción de Servicios Web(Web Services Descripcion Language - WSDL).REST define un set de principios arquitectónicos por los cuales se diseñan servicios web haciendo foco en los recursos del sistema, incluyendo cómo se accede al estado de dichos recursos y cómo se transfieren por HTTP hacia clientes escritos en diversos lenguajes.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (446, 470, 'Almacén de Eventos', 'Del inglés -Event sourcing- involucra el modelado de cambio de estados hechos a una aplicación como una secuencia inmutable o registro de eventos. \r\n\r\nEn lugar modificar el estado de la aplicación directamente, un almacén de eventos almacena el evento que lanzo el cambio de estado en un registro inmutable y modela los cambios de estados como respuestas a los eventos en el registro.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (447, 471, 'Modelación y Optimización', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (448, 472, 'Sistema de Información', 'Los sistemas de Información dan soporte a las operaciones empresariales, la gestión y la toma de decisiones, proporcionando a las personas la información que necesitan mediante el uso de las tecnologías de la información. ', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (449, 473, 'INTELIGENCIA DE NEGOCIOS', 'SE ENTIENDE POR INTELIGENCIA DE NEGOCIOS(BUSINESS INTELLIGENCE) AL CONJUNTO DE METODOLOGIAS , APLICACIONES, PRACTICAS Y CAPACIDADES ENFOCADAS A LA CREACION Y ADMINISTRACION DE LA INFORMACION QUE PERMITE TOMAR MEJORES DECISIONES A LOS USUARIOS DE UN ORGANIZACION.\r\nEN RESUMEN SE PUEDE UTILIZAR DATOS DE AYER Y HOY PARA TOMAR MEJORES DECISIONES MAÑANA.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (450, 474, 'Sistemas de Informacion', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (451, 475, 'Bots', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (452, 476, 'Cloud Computing', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (453, 477, 'Programacion movil', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (454, 478, 'Programación móvil', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (455, 479, 'Programación Movil', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (456, 480, 'Base de Datos,Aplicación Web y Sistemas de información', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (457, 481, 'Análisis de contenido de páginas web.', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (458, 482, 'Seguridad Informatica', 'Es el área relacionada con la informática y la telemática que se enfoca en la protección de la infraestructura computacional y todo lo relacionado con esta y, especialmente, la información contenida en una computadora o circulante a través de las redes de computadoras.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (459, 483, 'Recuperación de la Información ', 'Proceso donde se accede a una información previamente almacenada, mediante herramientas informáticas que permiten establecer ecuaciones de búsqueda específicas. Dicha información ha debido de ser estructura previamente a su almacenamiento.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (460, 484, 'Patrones de diseño', 'Los patrones de diseño de diagramas de clase son soluciones comprobadas a diferentes problemas bajo cierto contexto.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (461, 485, 'Servicio Movil Nativa', 'servicio del dispositivo movil nativa \r\n', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (462, 486, 'Data Warehouse y Mineria de Datos', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (463, 487, 'Data Mining, Data Science', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (464, 488, 'Realidad virtual', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (465, 489, 'Realidad mixta', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (466, 490, ' sistema de información', 'Un Sistema de Información es un conjunto de componentes que interactúan entre sí, orientado a la recolección, almacenamiento, procesamiento y recuperación de información.\r\nSe estudian las características resultantes de esas interacciones y qué mecanismos se pueden utilizar para el desarrollo y adaptación de estos sistemas de forma que puedan se explotados en las organizaciones con el mayor retorno posible.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (467, 491, 'Programación Móvil', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (468, 492, 'Análisis de video', 'Describe un amplio número de nuevas tecnologías y evoluciones en el campo de la vigilancia con vídeo y la seguridad.\r\nAlgunas aplicaciones del análisis de vídeo son la detección de objetos abandonados en lugares llenos de gente, controlar obras de arte en los museos y detectar vehículos no autorizados que ingresen a determinadas áreas. La detección de matrículas de vehículos, congestión de tránsito,tecnologias mas de reconocimiento facial.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (469, 493, 'Aplicacion web', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (470, 494, 'programacion Movil', 'programacion movil', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (471, 495, 'sistema gestion del conocimiento', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (472, 496, 'PROGRAMACIÓN MOVIL', 'desarrollo de aplicaciones para aparatos como celulares, smartphones, PDAs, PocketPCs y dispositivos con recursos limitados.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (473, 497, 'Aprendizaje en profundidad', '', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (474, 498, 'Algoritmos', 'Algoritmos pueden realizar calculos, procesamiento de datos y tareas de razonamiento automatizado.', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (475, 499, 'Optimizacion', 'Es la seleccion del mejor elemento con respecto a algun criterio de un conjunto de elementos disponibles.\r\n', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (476, 500, 'Aprendizaje automatico', 'Aprendizaje supervisado\r\nApredizaje no supervisado\r\nAprendizaje por refuerzo', NULL, NULL, NULL);
INSERT INTO `areas` VALUES (477, 501, 'Aplicacion WEB', 'Sistema de Informacion que esta en la Nube', NULL, NULL, NULL);
