INSERT INTO `profesional` 
VALUES 
(1 ,'Pablo Ramon','Azero','Azero',1,'pab.aze',4252439,0,'Interno','pabloazero@memi.umss.edu.bo',NULL,NULL,NULL),                                      
(2 ,'Vladimir','Costas','Costas',2,'vla.cos',4666037,0,'Interno','vcostas@cs.umss.edu.bo',NULL,NULL,NULL),
(3 ,'Corina Justina','Flores','Flores',1,'cor.flo',4252439,0,'Interno','corina@memi.umss.edu.bo',NULL,NULL,NULL),
(4 ,'Victor Hugo','Montaño','Montaño',1,'vic.mon',4233719,0,'Interno','victor@memi.umss.edu.bo',NULL,NULL,NULL),
(5 ,'Carla','Salazar','Salazar',3,'car.sal',4233719,0,'Interno','csalazar@memi.umss.edu.bo',NULL,NULL,NULL),
(6 ,'Henrry Frank','Villarroel','Villarroel',1,'hen.vil',77931275,0,'Interno','hvillarroel@memi.umss.edu.bo',NULL,NULL,NULL),
(7 ,'Samuel Roberto','Achá','Achá',5,'sam.ach',70719123,0,'Interno','cibo@supernet.com.bo',NULL,NULL,NULL),
(8 ,'Luis Roberto','Agreda','Agreda',5,'lui.agr',4529557,0,'Interno','luisagreda@hotmail.com',NULL,NULL,NULL),
(9 ,',Nancy Tatiana','Aparicio','Aparicio',2,'tat.apa',0,0,'Interno','aparicio@ucbcba.edu.bo',NULL,NULL,NULL),
(10,'Maria Leticia','Blanco','Blanco',1,'let.bla',4252439,0,'Interno','leticia@memi.umss.edu.bo',NULL,NULL,NULL),
(11,'Boris Marcelo','Calancha','Calancha',1,'bor.cal',4233719,0,'Interno','boris@fcyt.umss.edu.bo',NULL,NULL,NULL),
(12,'Indira Elva','Camacho','Camacho',2,'ind.cam',4529433,0,'Interno','agrofru@gmail.com',NULL,NULL,NULL),
(13,'David','Escalera','Escalera',1,'dav.esc',0,0,'Interno','descalera@cs.umss.edu.bo',NULL,NULL,NULL),
(14,'Juan Marcelo','Flores','Flores',1,'mar.flo',4233719,0,'Interno','marcelo@memi.umss.edu.bo',NULL,NULL,NULL),
(15,'K. Rolando','Jaldin','Jaldin',3,'rol.jal',100,0,'Interno','rjaldin@hotmail.com',NULL,NULL,NULL),
(16,'Ruperto','León','León',4,'root',4233719,0,'Interno','ruperto@cs.umss.edu.bo',NULL,NULL,NULL),
(17,'Carlos Benito','Manzur','Manzur',1,'car.man',4233719,0,'Interno','ca.manzu@umss.edu.bo',NULL,NULL,NULL),
(18,'Yony Richard','Montoya','Montoya',3,'yon.mon',71725138,0,'Interno','yony@setbol.net',NULL,NULL,NULL),
(19,'Patricia Elizabeth','Romero','Romero',3,'pat.rom',0,0,'Interno','paromeror@gmail.com',NULL,NULL,NULL),
(20,'Rose Mary','Salazar','Salazar',1,'ro.sa',4233719,0,'Interno','rsalazar@umss.edu.bo',NULL,NULL,NULL),
(21,'Roxana','Silva','Silva',1,'rox.sil',4233719,0,'Interno','tersil@supernet.com.bo',NULL,NULL,NULL),
(22,'Hernan','Ustariz','Ustariz',1,'her.ust',4233719,0,'Interno','hustariz@memi.umss.edu.bo',NULL,NULL,NULL),
(23,'Aidée','Vargas','Vargas',1,'aid.var',4233719,0,'Interno','aideevc@fcyt.umss.edu.bo',NULL,NULL,NULL),
(24,'Alvaro Hernando','Carrasco','Carrasco',1,'alv.car',4233719,0,'Interno','',NULL,NULL,NULL),
(25,'Raul','Catari','Catari',1,'rau.cat',4233719,0,'Interno','micorreo@yahoo.com',NULL,NULL,NULL),
(26,'Francisco','Choque','Choque',1,'fra.cho',4233719,0,'Interno',' uno@hotmail.com',NULL,NULL,NULL),
(27,'Carlos J. Alfredo','Cosio','Cosio',5,'alf.cos',4233719,0,'Interno','' ,NULL,NULL,NULL),
(28,'Walter','Cossio','Cossio',4,'wal.cos',4233719,0,'Interno',' cossio@hotmail.com',NULL,NULL,NULL),
(29,'Jorge','Davalos','Davalos',1,'jor.dav',4233719,0,'Interno',' ',NULL,NULL,NULL),
(30,'Juan A.','Fernandez','Fernandez',1,'jua.fer',4233719,0,'Interno',' ',NULL,NULL,NULL),
(31,'Maria Estela','Grilo','Grilo',1,'est.gri',4233719,0,'Interno',' ',NULL,NULL,NULL),
(32,'Victor','Gutierrez','Gutierrez',1,'vic.gut',4233719,0,'Interno',' ',NULL,NULL,NULL),
(33,'Mauricio','Hoepfner','Hoepfner',1,'mau.hoe',4233719,0,'Interno',' ',NULL,NULL,NULL),
(34,'Tito Anibal','Lima','Lima',4,'tit.lim',70744138,0,'Interno','tlima@quadraplastsrl.com',NULL,NULL,NULL),
(35,'Roberto Juan','Manchego','Manchego',5,'rob.man',4232189,0,'Interno','rmanchego@hotmail.com',NULL,NULL,NULL),
(36,'Julio','Medina','Medina',5,'jul.med',4233719,0,'Interno',' ',NULL,NULL,NULL),
(37,'Victor R.','Mejia','Mejia',1,'vic.mej',4233719,0,'Interno',' ',NULL,NULL,NULL),
(38,'Jose Roberto','Omonte','Omonte',5,'rob.omo',4233719,0,'Interno',' ',NULL,NULL,NULL),
(39,'Jose Gil','Omonte','Omonte',5,'jos.omo',4233719,0,'Interno',' ',NULL,NULL,NULL),
(40,'Omar David','Perez','Perez',4,'oma.per',4233719,0,'Interno','omar_perez_f@hotmail.com',NULL,NULL,NULL),
(41,'Ramiro','Rojas','Rojas',5,'ram.roj',4233719,0,'Interno',' ',NULL,NULL,NULL),                                                          
(42,'Jose Antonio','Soruco','Soruco',1,'jos.sor',4233719,0,'Interno',' ',NULL,NULL,NULL),
(43,'Fidel','Taborga','Taborga',1,'fid.tab',4233719,0,'Interno',' ',NULL,NULL,NULL),
(44,'Roberto','Valenzuela','Valenzuela',5,'rob.val',4233719,0,'Interno',' ',NULL,NULL,NULL),
(45,'Carmen Rosa','Garcia','Garcia',1,'car.gar',0,0,'Interno','carmenrosagarcia@hotmail.com',NULL,NULL,NULL),
(46,'Erika Patricia','Rodriguez','Rodriguez',3,'pat.rod',0,0,'Interno','akirebilbao@gmail.com ',NULL,NULL,NULL),
(47,'Mabel Gloria','Magariños','Magariños',5,'mab.mag',4234244,0,'Interno','mabelm@fcyt.umss.edu.bo',NULL,NULL,NULL),
(48,'Grover','Cussi','Cussi',1,'gro.cus',0,0,'Interno','gcussi@yahoo.com',NULL,NULL,NULL),
(49,'Jorge Walter','Orellana','Orellana',4,'jor.ore',0,0,'Interno','jw.orellana@umss.edu.bo',NULL,NULL,NULL),
(50,'Rosemary','Torrico','Torrico',3,'ros.tor',71778384,0,'Interno','rosemary@cs.umss.edu.bo',NULL,NULL,NULL),
(51,'Jimmy','Villarroel','Villarroel',5,'jim.vill',0,0,'Interno','jimmyvn_@hotmail.com',NULL,NULL,NULL),
(52,'Ligia Jacqueline','Aranibar','Aranibar',1,'lig.ara',0,0,'Interno','ligiajacqueline@hotmail.com',NULL,NULL,NULL),
(53,'Americo','Fiorilo','Fiorilo',4,'ame.fio',0,0,'Interno','amefio@gmail.com',NULL,NULL,NULL),
(54,'Jose Richard','Ayoroa','Ayoroa',5,'ric.ayo',0,0,'Interno','richard@correo.com',NULL,NULL,NULL),
(55,'Marco Antonio','Montecinos','Montecinos',3,'mar.mon',0,0,'Interno','markmcbo@gmail.com',NULL,NULL,NULL),
(56,'Christian','Villazon','Villazon',1,'villazon',0,0,'Interno','villazon@gmial.com',NULL,NULL,NULL),
(57,'Walter','Arispe','Arispe',5,'wal.ari',0,0,'Interno','santander@hotmail.com',NULL,NULL,NULL),
(58,'Alex Israel','Bustillos','Bustillos',1,'ale.bus',0,0,'Interno','bustillos@hotmail.com',NULL,NULL,NULL),
(59,'Cecilia Beatriz','Castro','Castro',1,'cec.cas',0,0,'Interno','castro@hotmail.com',NULL,NULL,NULL),
(60,'Maria Benita','Cespedes','Cespedes',1,'ben.ces',0,0,'Interno','cespedes@hotmail.com',NULL,NULL,NULL),
(61,'Alex D anchgelo','Choque','Choque',1,'ale.cho',0,0,'Interno','choque@hotmail.com',NULL,NULL,NULL),
(62,'David Alfredo','Delgadillo','Delgadillo',1,'alf.del',0,0,'Interno','delgadillo@hotmail.com',NULL,NULL,NULL),
(63,'David','Fernandez','Fernandez',5,'dav.fer',0,0,'Interno','fernandez@hotmail.com',NULL,NULL,NULL),
(64,'Juan Ruben','Garcia','Garcia',5,'rub.gar',0,0,'Interno','garcia@hotmail.com',NULL,NULL,NULL),
(65,'Osvaldo Walter','Gutierrez','Gutierrez',5,'osv.gut',0,0,'Interno','gutierrez@hotmail.com',NULL,NULL,NULL),
(66,'Gonzalo E. Antonio','Guzman','Guzman',5,'gon.guz',0,0,'Interno','guzman@hotmail.com',NULL,NULL,NULL),
(67,'Johnny','Herrera','Herrera',5,'joh.her',0,0,'Interno','herrera@hotmail.com',NULL,NULL,NULL),
(68,'Demetrio','Juchani','Juchani',5,'dem.juc',0,0,'Interno','juchani@hotmail.com',NULL,NULL,NULL),
(69,'Gualberto','Leon','Leon',5,'gua.leo',0,0,'Interno','leon@hotmail.com',NULL,NULL,NULL),
(70,'Marcelo Javier','Lucano','Lucano',1,'mar.luc',0,0,'Interno','lucano@hotmail.com',NULL,NULL,NULL),
(71,'Amilcar Saul','Martinez','Martinez',1,'ami.mar',0,0,'Interno','martinez@hotmail.com',NULL,NULL,NULL),
(72,'Ronald Edgar','Patiño','Patiño',5,'edg.pat',0,0,'Interno','patino@hotmail.com',NULL,NULL,NULL),
(73,'Magda Lena','Peeters','Peeters',1,'mag.pee',0,0,'Interno','peeters@hotmail.com',NULL,NULL,NULL),
(74,'Alfredo','Pericon','Pericon',5,'alf.per',0,0,'Interno','pericon@hotmail.com',NULL,NULL,NULL),
(75,'Abdon','Quiroz','Quiroz',5,'abd.qui',0,0,'Interno','quiroz@hotmail.com',NULL,NULL,NULL),
(76,'Juan Antonio','Rodriguez','Rodriguez',5,'ant.rod',0,0,'Interno','rodriguez@hotmail.com',NULL,NULL,NULL),
(77,'Ariel Antonio','Sarmiento','Sarmiento',5,'ari.sar',0,0,'Interno','sarmiento@hotmail.com',NULL,NULL,NULL),
(78,'Darlong Howard','Taylor','Taylor',1,'dar.tay',0,0,'Interno','taylor@hotmail.com',NULL,NULL,NULL),
(79,'Juan','Terrazas','Terrazas',5,'jua.ter',0,0,'Interno','terrazas@hotmail.com',NULL,NULL,NULL),
(80,'Marco Antonio','Vallejos','Vallejos',5,'mar.val',0,0,'Interno','vallejos@hotmail.com',NULL,NULL,NULL),
(81,'Ademar Marcelo','Vargas','Vargas',5,'mar.var',0,0,'Interno','vargas@hotmail.com',NULL,NULL,NULL),
(82,'Oscar A','Zabalaga','Zabalaga',5,'osc.zab',0,0,'Interno','zabalaga@hotmail.com',NULL,NULL,NULL),
(83,'Valentin','Laime','Laime',1,'val.lai',0,0,'Interno','laime@gmail.com',NULL,NULL,NULL);                                                                                   