
INSERT INTO `profesional` 
VALUES (1 ,'Pablo Ramon','Azero','Azero','Lic.',4252439,0,'pab.aze','Interno','pabloazero@memi.umss.edu.bo',NULL,NULL,NULL),                                      
(2 ,'Vladimir','Costas','Costas','Msc.',4666037,0,'vla.cos','Interno','vcostas@cs.umss.edu.bo',NULL,NULL,NULL),
(3 ,'Corina Justina','Flores','Flores','Lic.',4252439,0,'cor.flo','Interno','corina@memi.umss.edu.bo',NULL,NULL,NULL),
(4 ,'Victor Hugo','Montaño','Montaño','Lic.',4233719,0,'vic.mon','Interno','victor@memi.umss.edu.bo',NULL,NULL,NULL),
(5 ,'Carla','Salazar','Salazar','Msc. Lic.',4233719,0,'car.sal','Interno','csalazar@memi.umss.edu.bo',NULL,NULL,NULL),
(6 ,'Henrry Frank','Villarroel','Villarroel','Lic.',77931275,0,'hen.vil','Interno','hvillarroel@memi.umss.edu.bo',NULL,NULL,NULL),
(7 ,'Samuel Roberto','Achá','Achá','Ing.',70719123,0,'sam.ach','Interno','cibo@supernet.com.bo',NULL,NULL,NULL),
(8 ,'Luis Roberto','Agreda','Agreda','Ing.',4529557,0,'lui.agr','Interno','luisagreda@hotmail.com',NULL,NULL,NULL),
(9 ,',Nancy Tatiana','Aparicio','Aparicio','Msc.',0,0,'tat.apa','Interno','aparicio@ucbcba.edu.bo',NULL,NULL,NULL),
(10,'Maria Leticia','Blanco','Blanco','Lic.',4252439,0,'let.bla','Interno','leticia@memi.umss.edu.bo',NULL,NULL,NULL),
(11,'Boris Marcelo','Calancha','Calancha','Lic.',4233719,0,'bor.cal','Interno','boris@fcyt.umss.edu.bo',NULL,NULL,NULL),
(12,'Indira Elva','Camacho','Camacho','Msc.',4529433,0,'ind.cam','Interno','agrofru@gmail.com',NULL,NULL,NULL),
(13,'David','Escalera','Escalera','Lic.',0,0,'dav.esc','Interno','descalera@cs.umss.edu.bo',NULL,NULL,NULL),
(14,'Juan Marcelo','Flores','Flores','Lic.',4233719,0,'mar.flo','Interno','marcelo@memi.umss.edu.bo',NULL,NULL,NULL),
(15,'K. Rolando','Jaldin','Jaldin','Msc. Lic.',100,0,'rol.jal','Interno','rjaldin@hotmail.com',NULL,NULL,NULL),
(16,'Ruperto','León','León','Msc. Ing.',4233719,0,'root','Interno','ruperto@cs.umss.edu.bo',NULL,NULL,NULL),
(17,'Carlos Benito','Manzur','Manzur','Lic.',4233719,0,'car.man','Interno','ca.manzu@umss.edu.bo',NULL,NULL,NULL),
(18,'Yony Richard','Montoya','Montoya','Msc. Lic.',71725138,0,'yon.mon','Interno','yony@setbol.net',NULL,NULL,NULL),
(19,'Patricia Elizabeth','Romero','Romero','Msc. Lic.',0,0,'pat.rom','Interno','paromeror@gmail.com',NULL,NULL,NULL),
(20,'Rose Mary','Salazar','Salazar','Lic.',4233719,0,'ro.sa','Interno','rsalazar@umss.edu.bo',NULL,NULL,NULL),
(21,'Roxana','Silva','Silva','Lic.',4233719,0,'rox.sil','Interno','tersil@supernet.com.bo',NULL,NULL,NULL),
(22,'Hernan','Ustariz','Ustariz','Lic.',4233719,0,'her.ust','Interno','hustariz@memi.umss.edu.bo',NULL,NULL,NULL),
(23,'Aidée','Vargas','Vargas','Lic.',4233719,0,'aid.var','Interno','aideevc@fcyt.umss.edu.bo',NULL,NULL,NULL),
(24,'Alvaro Hernando','Carrasco','Carrasco','Lic.',4233719,0,'alv.car','Interno','',NULL,NULL,NULL),
(25,'Raul','Catari','Catari','Lic.',4233719,0,'rau.cat','Interno','micorreo@yahoo.com',NULL,NULL,NULL),
(26,'Francisco','Choque','Choque','Lic.',4233719,0,'fra.cho','Interno',' uno@hotmail.com',NULL,NULL,NULL),
(27,'Carlos J. Alfredo','Cosio','Cosio','Ing.',4233719,0,'alf.cos','Interno','' ,NULL,NULL,NULL),
(28,'Walter','Cossio','Cossio','Msc. Ing.',4233719,0,'wal.cos','Interno',' cossio@hotmail.com',NULL,NULL,NULL),
(29,'Jorge','Davalos','Davalos','Lic.',4233719,0,'jor.dav','Interno',' ',NULL,NULL,NULL),
(30,'Juan A.','Fernandez','Fernandez','Lic.',4233719,0,'jua.fer','Interno',' ',NULL,NULL,NULL),
(31,'Maria Estela','Grilo','Grilo','Lic.',4233719,0,'est.gri','Interno',' ',NULL,NULL,NULL),
(32,'Victor','Gutierrez','Gutierrez','Lic.',4233719,0,'vic.gut','Interno',' ',NULL,NULL,NULL),
(33,'Mauricio','Hoepfner','Hoepfner','Lic.',4233719,0,'mau.hoe','Interno',' ',NULL,NULL,NULL),
(34,'Tito Anibal','Lima','Lima','Msc. Ing.',70744138,0,'tit.lim','Interno','tlima@quadraplastsrl.com',NULL,NULL,NULL),
(35,'Roberto Juan','Manchego','Manchego','Ing.',4232189,0,'rob.man','Interno','rmanchego@hotmail.com',NULL,NULL,NULL),
(36,'Julio','Medina','Medina','Ing.',4233719,0,'jul.med','Interno',' ',NULL,NULL,NULL),
(37,'Victor R.','Mejia','Mejia','Lic.',4233719,0,'vic.mej','Interno',' ',NULL,NULL,NULL),
(38,'Jose Roberto','Omonte','Omonte','Ing.',4233719,0,'rob.omo','Interno',' ',NULL,NULL,NULL),
(39,'Jose Gil','Omonte','Omonte','Ing.',4233719,0,'jos.omo','Interno',' ',NULL,NULL,NULL),
(40,'Omar David','Perez','Perez','Msc. Ing.',4233719,0,'oma.per','Interno','omar_perez_f@hotmail.com',NULL,NULL,NULL),
(41,'Ramiro','Rojas','Rojas','Ing.',4233719,0,'ram.roj','Interno',' ',NULL,NULL,NULL),                                                          
(42,'Jose Antonio','Soruco','Soruco','Lic.',4233719,0,'jos.sor','Interno',' ',NULL,NULL,NULL),
(43,'Fidel','Taborga','Taborga','Lic.',4233719,0,'fid.tab','Interno',' ',NULL,NULL,NULL),
(44,'Roberto','Valenzuela','Valenzuela','Ing.',4233719,0,'rob.val','Interno',' ',NULL,NULL,NULL),
(45,'Carmen Rosa','Garcia','Garcia','Lic.',0,0,'car.gar','Interno','carmenrosagarcia@hotmail.com',NULL,NULL,NULL),
(46,'Erika Patricia','Rodriguez','Rodriguez','Msc. Lic.',0,0,'pat.rod','Interno','akirebilbao@gmail.com ',NULL,NULL,NULL),
(47,'Mabel Gloria','Magariños','Magariños','Ing.',4234244,0,'mab.mag','Interno','mabelm@fcyt.umss.edu.bo',NULL,NULL,NULL),
(48,'Grover','Cussi','Cussi','Lic.',0,0,'gro.cus','Interno','gcussi@yahoo.com',NULL,NULL,NULL),
(49,'Jorge Walter','Orellana','Orellana','Msc. Ing.',0,0,'jor.ore','Interno','jw.orellana@umss.edu.bo',NULL,NULL,NULL),
(50,'Rosemary','Torrico','Torrico','Msc. Lic.',71778384,0,'ros.tor','Interno','rosemary@cs.umss.edu.bo',NULL,NULL,NULL),
(51,'Jimmy','Villarroel','Villarroel','Ing.',0,0,'jim.vill','Interno','jimmyvn_@hotmail.com',NULL,NULL,NULL),
(52,'Ligia Jacqueline','Aranibar','Aranibar','Lic.',0,0,'lig.ara','Interno','ligiajacqueline@hotmail.com',NULL,NULL,NULL),
(53,'Americo','Fiorilo','Fiorilo','Msc. Ing.',0,0,'ame.fio','Interno','amefio@gmail.com',NULL,NULL,NULL),
(54,'Jose Richard','Ayoroa','Ayoroa','Ing.',0,0,'ric.ayo','Interno','richard@correo.com',NULL,NULL,NULL),
(55,'Marco Antonio','Montecinos','Montecinos','Msc. Lic.',0,0,'mar.mon','Interno','markmcbo@gmail.com',NULL,NULL,NULL),
(56,'Christian','Villazon','Villazon','Lic.',0,0,'villazon','Interno','villazon@gmial.com',NULL,NULL,NULL),
(57,'Walter','Arispe','Arispe','Ing.',0,0,'wal.ari','Interno','santander@hotmail.com',NULL,NULL,NULL),
(58,'Alex Israel','Bustillos','Bustillos','Lic.',0,0,'ale.bus','Interno','bustillos@hotmail.com',NULL,NULL,NULL),
(59,'Cecilia Beatriz','Castro','Castro','Lic.',0,0,'cec.cas','Interno','castro@hotmail.com',NULL,NULL,NULL),
(60,'Maria Benita','Cespedes','Cespedes','Lic.',0,0,'ben.ces','Interno','cespedes@hotmail.com',NULL,NULL,NULL),
(61,'Alex D anchgelo','Choque','Choque','Lic.',0,0,'ale.cho','Interno','choque@hotmail.com',NULL,NULL,NULL),
(62,'David Alfredo','Delgadillo','Delgadillo','Lic.',0,0,'alf.del','Interno','delgadillo@hotmail.com',NULL,NULL,NULL),
(63,'David','Fernandez','Fernandez','Ing.',0,0,'dav.fer','Interno','fernandez@hotmail.com',NULL,NULL,NULL),
(64,'Juan Ruben','Garcia','Garcia','Ing.',0,0,'rub.gar','Interno','garcia@hotmail.com',NULL,NULL,NULL),
(65,'Osvaldo Walter','Gutierrez','Gutierrez','Ing.',0,0,'osv.gut','Interno','gutierrez@hotmail.com',NULL,NULL,NULL),
(66,'Gonzalo E. Antonio','Guzman','Guzman','Ing.',0,0,'gon.guz','Interno','guzman@hotmail.com',NULL,NULL,NULL),
(67,'Johnny','Herrera','Herrera','Ing.',0,0,'joh.her','Interno','herrera@hotmail.com',NULL,NULL,NULL),
(68,'Demetrio','Juchani','Juchani','Ing.',0,0,'dem.juc','Interno','juchani@hotmail.com',NULL,NULL,NULL),
(69,'Gualberto','Leon','Leon','Ing.',0,0,'gua.leo','Interno','leon@hotmail.com',NULL,NULL,NULL),
(70,'Marcelo Javier','Lucano','Lucano','Lic.',0,0,'mar.luc','Interno','lucano@hotmail.com',NULL,NULL,NULL),
(71,'Amilcar Saul','Martinez','Martinez','Lic.',0,0,'ami.mar','Interno','martinez@hotmail.com',NULL,NULL,NULL),
(72,'Ronald Edgar','Patiño','Patiño','Ing.',0,0,'edg.pat','Interno','patino@hotmail.com',NULL,NULL,NULL),
(73,'Magda Lena','Peeters','Peeters','Lic.',0,0,'mag.pee','Interno','peeters@hotmail.com',NULL,NULL,NULL),
(74,'Alfredo','Pericon','Pericon','Ing.',0,0,'alf.per','Interno','pericon@hotmail.com',NULL,NULL,NULL),
(75,'Abdon','Quiroz','Quiroz','Ing.',0,0,'abd.qui','Interno','quiroz@hotmail.com',NULL,NULL,NULL),
(76,'Juan Antonio','Rodriguez','Rodriguez','Ing.',0,0,'ant.rod','Interno','rodriguez@hotmail.com',NULL,NULL,NULL),
(77,'Ariel Antonio','Sarmiento','Sarmiento','Ing.',0,0,'ari.sar','Interno','sarmiento@hotmail.com',NULL,NULL,NULL),
(78,'Darlong Howard','Taylor','Taylor','Lic.',0,0,'dar.tay','Interno','taylor@hotmail.com',NULL,NULL,NULL),
(79,'Juan','Terrazas','Terrazas','Ing.',0,0,'jua.ter','Interno','terrazas@hotmail.com',NULL,NULL,NULL),
(80,'Marco Antonio','Vallejos','Vallejos','Ing.',0,0,'mar.val','Interno','vallejos@hotmail.com',NULL,NULL,NULL),
(81,'Ademar Marcelo','Vargas','Vargas','Ing.',0,0,'mar.var','Interno','vargas@hotmail.com',NULL,NULL,NULL),
(82,'Oscar A','Zabalaga','Zabalaga','Ing.',0,0,'osc.zab','Interno','zabalaga@hotmail.com',NULL,NULL,NULL),
(83,'Valentin','Laime','Laime','Lic.',0,0,'val.lai','Interno','laime@gmail.com',NULL,NULL,NULL);                                                                                   